name: "Build & Test"

on: [push, workflow_dispatch]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Debug Binary
        run: make debug

      - name: Run Test Suite
        run: ./build/debug/pyro test tests/*.pyro

